### ISSUE TITLE
Store config files less permissive and usable on multiuser systems

### ISSUE THREAD

**Issue by yolk** [Ephigenia/mite-cli#2]
When using `mite config set [key] [value]` mite-cli stores the given values in a config.json file lovated inside node_modules/mite-cli. This has two issues:

1. The file config.json is world-readable by any user/process on my system and contains sensitive informations. The permissions should be 640 or even better just 600.

2. The file is located outside of my users home folder. Other users using the same machine will see/overwrite my mite-cli file. Maybe it would be better to use a file in ~/.mite-cli.json instead?

**Comment by Ephigenia** [comment]
This is in fact a bug as I never thought about where the file would be stored when installing mite-cli. I’m going to fix it in a way where the config file is stored in the user’s home directory.

**Comment by Ephigenia** [comment]
Fixed in v0.6.3
