### ISSUE TITLE
The project is still maintained?

### ISSUE THREAD

**Issue by daaanny90** [Ephigenia/mite-cli#237]
I use this CLI a lot but I see 7 PRs and no new commit from the maintainer since 2022. @Ephigenia do you plan to keep this project active?

**Comment by Ephigenia** [comment]
Thanks for using mite-cli a lot. I’m not using mite myself anymore for more than a year now. That might be the reason why I didn’t check the devbot updates or committed any new stuff. I’ll check this in the next days. You’re always welcome to contribute!

**Comment by Ephigenia** [comment]
@daaanny90 new version: https://github.com/Ephigenia/mite-cli/releases/tag/v1.10.4
