### ISSUE TITLE
Configuration still saved also after uninstall

### ISSUE THREAD

**Issue by daaanny90** [Ephigenia/mite-cli#91]
## Context

- MacOS Catalina 10.15.7
- mite-cli 1.5.0

## Description

The Idea was to try to fix the bug described in the issue #90 .
I uninstalled the mite-cli and cloned the repository. When I run `npm start` I get the same error described in the issue #90 , but I can't change the configuration because mite-cli is actually uninstalled.

### Expected Behavior

- Uninstall mite-cli
- Clone the repository
- run `npm start`
- Start debug a fresh new version of mite-cli

### Current Behavior

I still have the configuration of my old uninstalled mite-cli

## Steps to Reproduce

1. Install mite-cli with `npm install -g mite-cli`
2. Set up account and apiKey
3. Uninstall mite-cli with `npm uninstall -g mite-cli`
4. Clone the repository
5. Run `npm start`

At this point, you still use the configuration set up at point 2

**Comment by Ephigenia** [comment]
The configuration is stored in the user’s directory usually `~/.mite-cli.json` and is not deleted when mite-cli gets uninstalled. I’m not sure if it would be a good practise removing this file when mite-cli gets uninstalled using the npm "uninstall" hook as it might not be always the intention when uninstalling mite-cli. I’ll have to check other similar applications and how they handle such a case.

I’m also not sure if #90 would be solved if the configuration file is removed. But have to make additional checks.

**Comment by daaanny90** [comment]
alright. Just tried and removing the configuration file does not help. I would like to help to solve this bug but I'm not sure how can I set up a development environment to debug mite-cli.

`npm start` is not useful. Can you point me in the right direction?

**Comment by Ephigenia** [comment]
Unfortunately the CLI is not optimized for being debuggable very easy. Maybe you get some more debug information when you prepend `DEBUG=*` before running the CLI. You can also debug the current values from the config by running `mite config list` … When there’s no `~/.mite-cli.json` you should get the defaults: https://github.com/Ephigenia/mite-cli/blob/develop/source/config.js

**Comment by daaanny90** [comment]
I would like to contribute but if I can't set up a development environment I can't of course try and test my contributions.

My question was: how can a contributor set up the project in order to develop something? If I download the repo and use `npm start` I just get the errors of #90 or `Access denied. Please check your credentials.` if I use a subdomain. I am doing something wrong? Is not `npm start` the script to use to start the project?

**Comment by Ephigenia** [comment]
I think if you solve the issue in #90 you’ll be good to go. Just to make sure that you’re not missing something … 

Assuming you cloned your fork or this repo to `~/Development/mite-cli` then you’ll be able to run the different cli commands after setting up `apiKey` and `account` correctly.

Assuming you have cloned your fork or this repo to "~/Development/mite-cli"

```
cd ~/Development/mite-cli
npm run start -- config set apiKey <key>
npm run start -- config set account <subdomain>
npm run start -- --help
npm run start -- list
```

Note that also in this case the config will be stored in `~/.mite-cli.json`.

**Comment by Ephigenia** [comment]
The initial description of issue is intended. An uninstall of mite-cli won’t remove the configuration file as this would be a not common behavior. I’m closing this issue now.
